#!/bin/sh

commit_msg_file="$1"

# On ne valide que la première ligne (le subject)
first_line=$(head -n 1 "$commit_msg_file")

regex='^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z-]+\))?: .+$'

echo "$first_line" | grep -Eq "$regex"
status=$?

if [ $status -ne 0 ]; then
  echo "Message de commit invalide."
  echo "Format attendu : <type>(optional-scope): <description>"
  echo "Types autorisés : build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test"
  exit 1
fi

exit 0
